# Generated by Django 3.2.6 on 2023-02-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WardDetail',
            fields=[
                ('ward_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_size', models.IntegerField()),
                ('available_size', models.IntegerField()),
            ],
        ),
    ]
